config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
root 'top#index'
get 'notifications/index'

resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    resources :submit_requests , shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
  end
  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :blogs do
  resources :comments
  collection do
    post :confirm
  end
end
  get 'blogs' => 'blogs#index'

  resources :contacts, only: [:index, :new, :create] do
  collection do
      post :confirm
    end
  end
  get 'contacts/new' => 'contacts#index'

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/task.rb
class Task < ActiveRecord::Base
 belongs_to :user
 belongs_to :charge, class_name: 'User', foreign_key: 'charge_id'
 validates :title, presence: true
 has_many :submit_requests, dependent: :destroy
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
   before_action :authenticate_user!
   before_action :correct_user
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.where(user_id: params[:user_id]).where.not(done: true, status: 1)
                 .order(updated_at: :desc)
    @user = User.find(params[:user_id])
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new(user_id: params[:user_id], charge_id: params[:user_id])
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

      respond_to do |format|
        if @task.save
          format.html { redirect_to user_tasks_url, notice: 'タスクを登録しました。' }
          format.json { render :show, status: :created, location: @task }
        else
          format.html { render :new }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to user_tasks_url, notice: 'タスクを削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:user_id, :title, :content, :deadline, :charge_id, :done, :status)
    end
    def correct_user
      @user = User.find(params[:user_id])
      redirect_to(user_tasks_path(current_user)) unless current_user == @user
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for([@task.user, @task]) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.datetime_select :deadline %>
  </div>
  <%= f.hidden_field :charge_id %>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <%= f.select :status, [["未着手", "0"], ["対応中", "1"]] %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', user_task_path(@task.user, @task) %> |
<%= link_to 'Back', user_tasks_path(@task.user) %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Content</th>
      <th>Deadline</th>
      <th>Charge</th>
      <th>Done</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.user.name %></td>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= task.deadline %></td>
        <td><%= task.charge_id %></td>
        <td><%= if task.done? then "完了" else "未完了" end %></td>
        <td><%= task.status == 1? "対応中" : "未着手" %></td>
        <td><%= link_to 'Show', user_task_path(task.user, task) %></td>
<td><%= link_to 'Edit', edit_user_task_path(task.user, task) %></td>
<td><%= link_to 'Destroy', user_task_path(task.user, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_user_task_path(@user) %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', user_tasks_path(@task.user_id) %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @task.user.email %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @task.deadline %>
</p>

<p>
  <strong>Charge:</strong>
  <%= @task.charge.name %>
</p>

<p>
  <strong>Done:</strong>
  <%= if @task.done? then "完了" else "未完了" end %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status == 1? "対応中" : "未着手" %>
</p>

<%= link_to 'Edit', edit_user_task_path(@task.user, @task) %> |
<%= link_to 'Back', user_tasks_path(@task.user) %>