config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
root 'top#index'
get 'notifications/index'

resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    resources :submit_requests , shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
  end
  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :blogs do
  resources :comments
  collection do
    post :confirm
  end
end
  get 'blogs' => 'blogs#index'

  resources :contacts, only: [:index, :new, :create] do
  collection do
      post :confirm
    end
  end
  get 'contacts/new' => 'contacts#index'

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  has_many :blogs, dependent: :destroy
         # CommentモデルのAssociationを設定
  has_many :comments, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower
  has_many :tasks, dependent: :destroy
  has_many :submit_requests, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

         #指定のユーザをフォローする
       def follow!(other_user)
         relationships.create!(followed_id: other_user.id)
       end

       #フォローしているかどうかを確認する
       def following?(other_user)
         relationships.find_by(followed_id: other_user.id)
       end

       def unfollow!(other_user)
       relationships.find_by(followed_id: other_user.id).destroy
       end
       def friend
           followers & followed_users
         end
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
user.skip_confirmation!
  user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email || "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20],
      )

      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    @user.skip_confirmation!
    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)
@user.skip_confirmation!
    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: "btn btn-large btn-primary" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "つながりを解除", class: "btn btn-large" %>
    <% end %>
  <% end %>
</div>

app/views/users/_followed_users.html.erb
<h1><%=user.name%>のフォローしている人</h1>
   <% user.followed_users.each do |followed_user|%>
      <p class="center">ユーザー名<%= followed_user.name %></p>
  <% end %>

app/views/users/_followers.html.erb
  <h1><%=user.name%>のフォロワー</h1>
   <% user.followers.each do |followers|%>
      <p class="center">ユーザー名<%= followers.name %></p>
  <% end %>

app/views/users/index.html.erb
<div class="container">
  <h2>ユーザー</h2>
  <% @users.each do |user| %>
      <div class="container-child col-md-2 col-sm-4 col-xs-6 ">
        <%= profile_img(user) %>
        <%= user.name %>
        <p><%= link_to '詳細', user_path(user) %></p>
        <%= render 'follow_form', user: user %>
      </div>

      <% if user.id != current_user.id %>
  <li>
    <div class="item">
      <%= link_to user.name, user %>
      <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
    </div>
    <%= render partial: 'follow_form', locals: { user: user } if signed_in?   %>
  </li>
<% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="blog-text">
      <p class="left"><%= profile_img(@user) %></p>
      <p class="left"><strong>名前</strong></p>
      <p class="left"><%= @user.name %></p>
      <p class="left"><strong>eメール</strong></p>
      <p class="left"><%= @user.email %></p>
      <p class="right">
        <strong>登録時間:</strong>
        <%= @user.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
</div>

<%= render partial: 'followed_users', locals: {user: @user}%>
<%= render partial: 'followers', locals: {user: @user}%>