config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
root 'top#index'
get 'notifications/index'

resources :users, only: [:index, :show, :edit, :update] do
    resources :tasks
    resources :submit_requests , shallow: true do
      get 'approve'
      get 'unapprove'
      get 'reject'
      collection do
        get 'inbox'
      end
    end
  end
  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :blogs do
  resources :comments
  collection do
    post :confirm
  end
end
  get 'blogs' => 'blogs#index'

  resources :contacts, only: [:index, :new, :create] do
  collection do
      post :confirm
    end
  end
  get 'contacts/new' => 'contacts#index'

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/submit_request.rb
class SubmitRequest < ActiveRecord::Base
  belongs_to :task
  belongs_to :user
  belongs_to :charger, class_name: 'User', foreign_key: 'charge_id'
end

app/controllers/submit_requests_controller.rb
class SubmitRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_submit_request, only: [:show, :edit, :update, :destroy]
  before_action :submit_params,only: [:approve, :unapprove]

  def index
  @submit_requests = SubmitRequest.where(user_id: current_user.id).order(updated_at: :desc)

end

def new
  # 相互フォローユーザー
  @users = current_user.friend
  # 自分が作成した未完了タスク
  @tasks = current_user.tasks.where(done: false)
  # フォーム送信用に取得
  @user = current_user
  # リクエスト新規作成用
  @submit_request = current_user.submit_requests.build(status: 1)
end

def create
  @submit_request = SubmitRequest.new(submit_request_params)
  respond_to do |format|
    if @submit_request.save
      @submit_request.task.update(status: 1)
      format.html { redirect_to user_submit_requests_path(current_user.id,@submit_request), notice: '依頼を送信しました。' }
      format.json { render :show, status: :created, location: @submit_request }
    else
      format.html { render :new }
      format.json { render json: @submit_request.errors, status: :unprocessable_entity }
    end
  end
end

  def show
  end

  def edit
    # 相互フォローユーザー
    @users = current_user.friend
    # 自分が作成した未完了タスク
    @tasks = current_user.tasks.where(done: false)
end

def update
  respond_to do |format|
    if @submit_request.update(submit_request_params)
     @submit_request.task.update(charge_id: submit_request_params[:charge_id])
     format.html { redirect_to user_submit_requests_path(current_user.id, @submit_request), notice: '依頼を編集しました。'}
     format.json { render :show, status: :ok, location: @submit_request }
   else
    format.html { render :edit }
    format.json { render json: @submit_request.errors, status: :unprocessable_entity }
    end
  end
end

  def destroy
  end

  def approve
    @submit_request.update(status: 2)
    @submit_request.task.update(status: 2)
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).order(updated_at: :desc)
    respond_to do |format|
      format.js { render :reaction_inbox }
    end
  end

  def unapprove
    @submit_request.update(status: 9)
    @submit_request.task.update(status: 9, charge_id: @submit_request.user_id)
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).order(updated_at: :desc)
    respond_to do |format|
      format.js { render :reaction_inbox }
    end
  end


  def reject
    @submit_request.update(status: 8)
    @submit_request.task.update(status: 8, charge_id: current_user.id)
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).order(updated_at: :desc)
    respond_to do |format|
      format.js { render :reaction_inbox }
    end
  end

  def inbox
    @submit_requests = SubmitRequest.where(charge_id: current_user.id).order(updated_at: :desc)
  end
  private

  def submit_request_params
    params.require(:submit_request).permit(:task_id, :user_id, :charge_id, :status, :message)
  end
  def set_submit_request
    @submit_request = SubmitRequest.find(params[:id])
  end
  def submit_params
    @submit_request = SubmitRequest.find(params[:submit_request_id].to_i)
 end
end

app/helpers/submit_requests_helper.rb
module SubmitRequestsHelper
  def status_display_name(status)
    case status
      when 1
        '未承認'
      when 2
        '承認済'
      when 8
        '取消済'
      when 9
        '却下'
    end
  end

  def done_display_name(done)
    done ? '完了' : '未完了'
  end
end

app/views/submit_requests/_form.html.erb
<%= form_for([@user, @submit_request]) do |f| %>
  <p>
    <%= f.collection_select :task_id, @tasks, :id, :title, {}, class: "form-control title" %>
    <%= f.collection_select :charge_id, @users, :id, :name, {}, class: "form-control" %>
  </p>
  <p><%= f.text_area :message, placeholder: "依頼メッセージ", size: "50-20", class:"form-control" %></p>
  <p><%= f.hidden_field :user_id %></p>
  <p><%= f.hidden_field :status %></p>
  <div class="button-panel row">
    <p><%= f.submit "依頼する", class: "button col-xs-12" %></p>
  </div>
<% end %>
<%= link_to '戻る', user_submit_requests_path(current_user) %>

app/views/submit_requests/_submit_requests_list.html.erb
<% if @submit_requests.present? %>
    <div class="task col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-12 table-responsive">
      <table class="table table-hover">
        <thead>
        <tr>
          <th>登録者</th>
          <th>タイトル</th>
          <th>担当者</th>
          <th>依頼日</th>
          <th>ステータス</th>
          <th>状況</th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% submit_requests.each do |submit_request| %>
            <tr>
              <td><%= submit_request.user.name if submit_request.user.present? %></td>
              <td><%= submit_request.task.title %></td>
              <% if submit_request.charge_id == current_user.id %>
                  <td>(自分)</td>
              <% else %>
                  <td><%= submit_request.charger.name %></td>
              <% end %>
              <td><%= submit_request.created_at.strftime("%y/%m/%d") %></td>
              <td><%= status_display_name(submit_request.status) %></td>
              <td><%= done_display_name(submit_request.task.done) %></td>
              <td data-featherlight="#<%= (submit_request.id) %>"><%= link_to 'メッセージ', submit_request_path(submit_request) %></td>
              <% if submit_request.charge_id == current_user.id %>
                  <td>
                    <%= link_to '承認', submit_request_approve_path(submit_request), remote: true %>
                    <%= link_to '却下', submit_request_unapprove_path(submit_request), remote: true %>
                    <%= link_to '依頼を取り消す', submit_request_reject_path(submit_request), data: submit_request.id, remote: true if submit_request.status == 1 %>
                  </td>
              <% end %>
              <% if submit_request.user_id == current_user.id %>
                  <td>
                    <%= link_to '編集', edit_submit_request_path(submit_request) %>
                    <%= link_to '削除', submit_request_path(submit_request), method: :delete, remote: true, data: { confirm: '本当に削除していいですか？' } %>
                  </td>
              <% end %>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
<% end %>

app/views/submit_requests/approve.html.erb
<h1>SubmitRequests#approve</h1>
<p>Find me in app/views/submit_requests/approve.html.erb</p>

app/views/submit_requests/create.html.erb
<h1>SubmitRequests#create</h1>
<p>Find me in app/views/submit_requests/create.html.erb</p>

app/views/submit_requests/destroy.html.erb
<h1>SubmitRequests#destroy</h1>
<p>Find me in app/views/submit_requests/destroy.html.erb</p>

app/views/submit_requests/edit.html.erb
<div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
  <h2>依頼編集</h2>
  <%= render 'form' %>
</div>

app/views/submit_requests/inbox.html.erb
<div class="container">
  <%= link_to '依頼一覧に戻る', user_submit_requests_path %>
  <div class="inbox_list_<%= current_user.id %>" id="inbox_list_<%= current_user.id %>" >
    <%= render 'submit_requests_list', submit_requests: @submit_requests %>
  </div>
</div>

app/views/submit_requests/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <%= link_to '新規依頼', new_user_submit_request_path %>
  <%= link_to '依頼されている一覧', inbox_user_submit_requests_path %>
  <div id="submit_requests_<%= current_user.id %>" >
    <%= render 'submit_requests_list', submit_requests: @submit_requests %>
  </div>
</div>

app/views/submit_requests/new.html.erb
<div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
  <div>
    <h2>依頼する内容</h2>
    <div>
      <% if @users.blank? %>
        依頼するユーザーがいません。
      <% elsif current_user.tasks.present? %>
        <%= render 'form' %>
      <% else %>
        依頼できるものがありません。
      <% end %>
    </div>
  </div>
</div>

app/views/submit_requests/reaction_inbox.js.erb
$("#inbox_list_<%= current_user.id %>").html("<%= j(render 'submit_requests_list', submit_requests: @submit_requests) %>");
$("#submit_requests_<%= current_user.id %>").html("<%= j(render 'submit_requests_list', submit_requests: @submit_requests) %>")

app/views/submit_requests/reject.html.erb
<h1>SubmitRequests#reject</h1>
<p>Find me in app/views/submit_requests/reject.html.erb</p>

app/views/submit_requests/show.html.erb
<h1>SubmitRequests#show</h1>
<p>Find me in app/views/submit_requests/show.html.erb</p>

app/views/submit_requests/unapprove.html.erb
<h1>SubmitRequests#unapprove</h1>
<p>Find me in app/views/submit_requests/unapprove.html.erb</p>

app/views/submit_requests/update.html.erb
<h1>SubmitRequests#update</h1>
<p>Find me in app/views/submit_requests/update.html.erb</p>